// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VINWMIVehicles.Data;

#nullable disable

namespace VINWMIVehicles.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    partial class VehicleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VINWMIVehicles.Domain.Geography.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IsoCode2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("IsoCode3")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameLocal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode2")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Geography.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VinChars")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Manufacturers.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("Dissolved")
                        .HasColumnType("integer");

                    b.Property<int?>("Founded")
                        .HasColumnType("integer");

                    b.Property<string>("HeadquartersCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameLocal")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NameOfficial")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ParentManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("StockSymbol")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ParentManufacturerId");

                    b.ToTable("Manufacturers", (string)null);
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Manufacturers.WmcEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("ValidFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("ValidTo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("CodeType", "Code");

                    b.ToTable("WmcEntries", (string)null);
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Manufacturers.WmiAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("VehicleTypeScope")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Wmi")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int?>("YearFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("YearTo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Wmi", "YearFrom", "YearTo");

                    b.ToTable("WmiAssignments", (string)null);
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("Discontinued")
                        .HasColumnType("integer");

                    b.Property<int?>("Founded")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameOfficial")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OriginCountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("OriginCountryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("GenerationFrom")
                        .HasColumnType("integer");

                    b.Property<string>("GenerationName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("GenerationTo")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("VehicleBodyStyleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("VehicleBodyStyleId");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.VehicleBodyStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TypicalDoorOptions")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("VehicleBodyStyles", (string)null);
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.VehicleClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("VehicleClasses", (string)null);
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Acceleration0100s")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<int?>("Co2gKm")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("DisplacementCc")
                        .HasColumnType("integer");

                    b.Property<int?>("Doors")
                        .HasColumnType("integer");

                    b.Property<string>("DriveType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EngineCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("FuelConsumptionL100km")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<string>("FuelType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("Gears")
                        .HasColumnType("integer");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("integer");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxSpeedKmh")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("PowerKw")
                        .HasColumnType("integer");

                    b.Property<int?>("Seats")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TorqueNm")
                        .HasColumnType("integer");

                    b.Property<string>("TransmissionType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Trim")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VdsPattern")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int?>("WeightKg")
                        .HasColumnType("integer");

                    b.Property<int?>("WidthMm")
                        .HasColumnType("integer");

                    b.Property<int?>("YearFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("YearTo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("VdsPattern")
                        .HasFilter("\"VdsPattern\" IS NOT NULL");

                    b.ToTable("VehicleModels", (string)null);
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("VehicleClassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleClassId");

                    b.ToTable("VehicleTypes", (string)null);
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vin.VinDecodeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedFields")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("DecodedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("VinRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VinRecordId");

                    b.ToTable("VinDecodeHistories", (string)null);
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vin.VinRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<char>("CheckDigit")
                        .HasColumnType("character(1)");

                    b.Property<Guid?>("CountryOfManufactureId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecodedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecodedSource")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("integer");

                    b.Property<char>("ModelYearChar")
                        .HasColumnType("character(1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<char>("PlantCode")
                        .HasColumnType("character(1)");

                    b.Property<string>("RawApiResponse")
                        .HasColumnType("text");

                    b.Property<string>("SequentialNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationErrors")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Vds")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<Guid?>("VehicleModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Vis")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Wmi")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.HasIndex("CountryOfManufactureId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VehicleModelId");

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.HasIndex("Wmi");

                    b.ToTable("VinRecords", (string)null);
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Geography.Country", b =>
                {
                    b.HasOne("VINWMIVehicles.Domain.Geography.Region", "Region")
                        .WithMany("Countries")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Manufacturers.Manufacturer", b =>
                {
                    b.HasOne("VINWMIVehicles.Domain.Geography.Country", "Country")
                        .WithMany("Manufacturers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VINWMIVehicles.Domain.Manufacturers.Manufacturer", "ParentManufacturer")
                        .WithMany("Subsidiaries")
                        .HasForeignKey("ParentManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");

                    b.Navigation("ParentManufacturer");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Manufacturers.WmcEntry", b =>
                {
                    b.HasOne("VINWMIVehicles.Domain.Manufacturers.Manufacturer", "Manufacturer")
                        .WithMany("WmcEntries")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Manufacturers.WmiAssignment", b =>
                {
                    b.HasOne("VINWMIVehicles.Domain.Manufacturers.Manufacturer", "Manufacturer")
                        .WithMany("WmiAssignments")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.Brand", b =>
                {
                    b.HasOne("VINWMIVehicles.Domain.Manufacturers.Manufacturer", "Manufacturer")
                        .WithMany("Brands")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VINWMIVehicles.Domain.Geography.Country", "OriginCountry")
                        .WithMany("Brands")
                        .HasForeignKey("OriginCountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manufacturer");

                    b.Navigation("OriginCountry");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.Series", b =>
                {
                    b.HasOne("VINWMIVehicles.Domain.Vehicles.Brand", "Brand")
                        .WithMany("Series")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VINWMIVehicles.Domain.Vehicles.VehicleBodyStyle", "VehicleBodyStyle")
                        .WithMany("Series")
                        .HasForeignKey("VehicleBodyStyleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("VehicleBodyStyle");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.VehicleBodyStyle", b =>
                {
                    b.HasOne("VINWMIVehicles.Domain.Vehicles.VehicleType", "VehicleType")
                        .WithMany("BodyStyles")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.VehicleModel", b =>
                {
                    b.HasOne("VINWMIVehicles.Domain.Vehicles.Series", "Series")
                        .WithMany("Models")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.VehicleType", b =>
                {
                    b.HasOne("VINWMIVehicles.Domain.Vehicles.VehicleClass", "VehicleClass")
                        .WithMany("VehicleTypes")
                        .HasForeignKey("VehicleClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VehicleClass");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vin.VinDecodeHistory", b =>
                {
                    b.HasOne("VINWMIVehicles.Domain.Vin.VinRecord", "VinRecord")
                        .WithMany("DecodeHistory")
                        .HasForeignKey("VinRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VinRecord");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vin.VinRecord", b =>
                {
                    b.HasOne("VINWMIVehicles.Domain.Geography.Country", "CountryOfManufacture")
                        .WithMany()
                        .HasForeignKey("CountryOfManufactureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VINWMIVehicles.Domain.Manufacturers.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VINWMIVehicles.Domain.Vehicles.VehicleModel", "VehicleModel")
                        .WithMany("VinRecords")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CountryOfManufacture");

                    b.Navigation("Manufacturer");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Geography.Country", b =>
                {
                    b.Navigation("Brands");

                    b.Navigation("Manufacturers");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Geography.Region", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Manufacturers.Manufacturer", b =>
                {
                    b.Navigation("Brands");

                    b.Navigation("Subsidiaries");

                    b.Navigation("WmcEntries");

                    b.Navigation("WmiAssignments");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.Brand", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.Series", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.VehicleBodyStyle", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.VehicleClass", b =>
                {
                    b.Navigation("VehicleTypes");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.VehicleModel", b =>
                {
                    b.Navigation("VinRecords");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vehicles.VehicleType", b =>
                {
                    b.Navigation("BodyStyles");
                });

            modelBuilder.Entity("VINWMIVehicles.Domain.Vin.VinRecord", b =>
                {
                    b.Navigation("DecodeHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
